name: Build and deploy Hugo site to S3

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"
        type: choice
        options:
          - info
          - warning
          - debug
      #   tags:
      #     description: "Test scenario tags"
      #     required: false
      #     type: boolean
      environment:
        description: "Environment to run tests against"
        type: environment
        required: true

# env:
#   AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#   AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#   AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}
#   AWS_S3_BUCKET: ${{ vars.AWS_S3_BUCKET }}
#   AWS_CLOUDFRONT_DISTRIBUTION_ID: ${{ vars.AWS_CLOUDFRONT_DISTRIBUTION_ID }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    defaults:
      run:
        working-directory: ./site
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod
          lfs: true # Fetch images and other binary files

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "latest"

      - name: Build
        run: hugo --minify

      - name: Tar public folder
        run: tar -zcvf public.tar.gz public

      - uses: actions/upload-artifact@v3
        with:
          name: site
          path: site/public.tar.gz

  deploy:
    needs: build
    strategy:
      fail-fast: true
      matrix:
        target: [Development, Production]
    uses: ./.github/workflows/deployment.yml
    with:
      target-env: ${{ matrix.target }}
      AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}
      AWS_S3_BUCKET: ${{ vars.AWS_S3_BUCKET }}
      AWS_CLOUDFRONT_DISTRIBUTION_ID: ${{ vars.AWS_CLOUDFRONT_DISTRIBUTION_ID }}
    secrets: inherit
