name: Reusable Build and Deploy Workflow

on:
  workflow_call:
    inputs:
      target-env:
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

jobs:
  build-deploy:
    name: Build and Deploy to ${{ inputs.target-env }}
    runs-on: ubuntu-22.04
    environment:
      name: ${{ inputs.target-env }}
    defaults:
      run:
        working-directory: ./site

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod
          lfs: true # Fetch images and other binary files

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "latest"
          extended: true

      - name: Load Base URL, Bucket, CloudFront Distribution ID into config
        run: |
          sed -i "s|BASE_URL_PLACEHOLDER|${{ vars.BASE_URL }}|g" ./config.yaml
          sed -i "s|BUCKET_PLACEHOLDER|${{ vars.AWS_S3_BUCKET }}|g" ./config.yaml
          sed -i "s|CLOUDFRONT_DISTRIBUTION_ID_PLACEHOLDER|${{ vars.AWS_CLOUDFRONT_DISTRIBUTION_ID }}|g" ./config.yaml

      - name: Build
        run: hugo --minify

      - name: Cat out config lines
        run: |
          cat ./config.yaml | grep -E 'baseURL|s3://|cloudFrontDistributionID'

      - name: Deploy
        run: hugo deploy --maxDeletes -1 --invalidateCDN
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
